Smastad/Smastad/Controllers/CitizenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Smastad.Controllers
{
  public class CitizenController : Controller
  {
    // GET: /<controller>/
    public IActionResult validate()
    {
      return View();
    }

    // GET: /<controller>/
    public IActionResult thanks()
    {
      return View();
    }
  }
}

Smastad/Smastad/Controllers/CoordinatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Smastad.Controllers
{
  public class CoordinatorController : Controller
  {
    public IActionResult coordinator()
    {
      return View();
    }

    public IActionResult crimeCoordinator()
    {
      return View();
    }

    public IActionResult reportCrime()
    {
      return View();
    }

    public IActionResult thanks()
    {
      return View();
    }

    public IActionResult validate()
    {
      return View();
    }
  }
}

Smastad/Smastad/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Smastad.Controllers
{
  public class HomeController : Controller
  {
    // GET: /<controller>/
    public IActionResult Index()
    {
      return View();
    }


  }
}

Smastad/Smastad/Controllers/InvestigatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace Smastad.Controllers
{
    public class InvestigatorController : Controller
    {
        // GET: /<controller>/
        public IActionResult investigator()
        {
            return View();
        }

        public IActionResult crimeInvestigator()
        {
          return View();
        }
  }
}

Smastad/Smastad/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Smastad.Controllers
{
  public class LogInController : Controller
  {
    // GET: /<controller>/
    public IActionResult logIn()
    {
      return View();
    }
  }
}

Smastad/Smastad/Controllers/ManagerController.cs
using Microsoft.AspNetCore.Mvc;

namespace Smastad.Controllers
{
  public class ManagerController : Controller
  {
    // GET: /<controller>/
    public IActionResult manager() // Should be named start instead of manager
    {
      return View();
    }

    public IActionResult crimeManager()
    {
      return View();
    }
  }
}

Smastad/Smastad/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace Smastad.Controllers
{
  public class ServiceController : Controller
  {
    // GET: /<controller>/
    public IActionResult service()
    {
      return View();
    }
  }
}

Smastad/Smastad/Views/Citizen/Validate.cshtml
@{
}

<nav>
    <ul>
        <li><a href="../index.html">Hem</a></li>
        <li><a href="services.html">Tjänster</a></li>
        <li><a href="faq.html">FAQ</a></li>
        <li><a href="contact.html">Kontakt</a></li>
        <li class="right"><a class="login" href="../login.html">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <section id="mainColumn">
        <h2>Din anmälan av miljöbrott</h2>
        <p class="label">
            Vänligen läs igenom din anmälan och se att allt är okej.<br />
            Om något är fel, gå tillbaka och ändra. Annars välj Bekräfta.
        </p>
        <p><span class="label">Var har brottet skett någonstans?</span><br />Skogslunden vid Jensens gård</p>
        <p><span class="label">Vilken typ av brott?</span><br />Sopor i massor ligger där</p>
        <p><span class="label">När skedde brottet?</span><br />Vet inte</p>
        <p><span class="label">Ditt namn (för- och efternamn):</span><br />Maja Färjedal</p>
        <p><span class="label">Din telefon:</span><br />432-554 55 22</p>
        <p><span class="label">Mer information:</span><br />Jag upptäckte soporna på en promenad den 24 april</p>
        <p><input class="button" value="Tillbaka" onclick="location.href='@Url.Action("Index", "Home")'" /> 
        <input class="button" value="Bekräfta" onclick="location.href='@Url.Action("thanks", "Citizen")'" /></p>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="../images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="../images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="../images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="../images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="../images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="../images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="../images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="../images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Contact/Contact.cshtml
@{
}

<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Service" asp-action="service"> Tjänster</a></li>
        <li><a asp-controller="FAQ" asp-action="faq">FAQ</a></li>
        <li><a asp-controller="Contact" asp-action="contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="LogIn" asp-action="logIn">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <section id="mainColumn">
        <h2>Kontaktuppgifter</h2>
        <p><span class="label">Besöksadress:</span> Storgatan 42</p>
        <p><span class="label">Postadress:</span> Box 10, 909 00 Småstad</p>
        <p><span class="label">Mail:</span> miljoboven@smastad.nu</p>
        <p><span class="label">Telefon:</span> 432-500 10 00</p>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Coordinator/Coordinator.cshtml
@{
}
<nav>
    <ul>
        <li><a asp-controller="Coordinator" asp-action="coordinator" class="reports">Start(Ärenden)</a></li>
        <li><a asp-controller="Coordinator" asp-action="reportCrime" class="reportAdd">Rapportera brott</a></li>
        <li class="right"><a asp-controller="Home" asp-action="Index" class="logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <h2>Ärenden</h2>
    <p class="info">Du är inloggad som samordnare</p>

    <table id="managerForm">
        <tr>
            <td class="label">Välj status:</td>
            <td class="label">Välj avdelning:</td>
            <td>&nbsp;</td>
            <td class="label">Ärendenummer:</td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <select name="status">
                    <option selected="selected">Välj alla</option>
                    <option value="stat0">Inrapporterad</option>
                    <option value="stat1">Ingen åtgärd</option>
                    <option value="stat2">Påbörjad</option>
                    <option value="stat3">Klar</option>
                </select>
            </td>
            <td>
                <select name="department">
                    <option selected="selected">Välj alla</option>
                    <option value="teknik">Tekniska avloppshanteringen</option>
                    <option value="klimat">Klimat och energi</option>
                    <option value="miljo">Miljö och Hälsoskydd</option>
                    <option value="natur">Natur och Skogsvård</option>
                    <option value="avfall">Renhållning och Avfall</option>
                </select>
            </td>
            <td><input class="button" type="submit" value="Hämta lista" /></td>
            <td><input name="casenumber" /></td>
            <td><input class="button" type="submit" value="Sök" /></td>
        </tr>
    </table>

    <!--Nedan ser man en lista på ärenden-->
    <table>
        <tr>
            <th>Ärende anmält</th>
            <th>Ärendenummer</th>
            <th>Miljöbrott</th>
            <th>Status</th>
            <th>Avdelning</th>
            <th>Handläggare</th>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0201</a></td>
            <td>Oljeutsläpp</td>
            <td>Ej startad</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ingen utredare satt</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0202</a></td>
            <td>Oljeutsläpp</td>
            <td>Pågående</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ada Bengtsson</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0203</a></td>
            <td>Oljeutsläpp</td>
            <td>Ej startad</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ingen utredare satt</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0204</a></td>
            <td>Oljeutsläpp</td>
            <td>Ej startad</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ingen utredare satt</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0205</a></td>
            <td>Oljeutsläpp</td>
            <td>Pågående</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Bengt Cederström</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0206</a></td>
            <td>Oljeutsläpp</td>
            <td>Ej startad</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ingen utredare satt</td>
        </tr>
        <tr>
            <td>2014-05-01</td>
            <td><a asp-controller="Coordinator" asp-action="crimeCoordinator">2014-45-0206</a></td>
            <td>Oljeutsläpp</td>
            <td>Ej startad</td>
            <td>Tekniska avloppshanteringen</td>
            <td>Ingen utredare satt</td>
        </tr>
    </table>


    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Coordinator/CrimeCoordinator.cshtml
@{
}
<nav>
    <ul>
        <li><a asp-controller="Coordinator" asp-action="coordinator" class="reports">Start(Ärenden)</a></li>
        <li><a asp-controller="Coordinator" asp-action="reportCrime" class="reportAdd">Rapportera brott</a></li>
        <li class="right"><a asp-controller="Home" asp-action="Index" class="logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <h2>Detaljer för ärendet</h2>
    <p class="info">Du är inloggad som samordnare</p>
    <h3>Ärende: 2014-45-0201</h3>
    <section id="leftColumn">
        <h3>Anmälan</h3>
        <p>
            <span class="label">Typ av brott: </span><br />
            Nedskräpning
        </p>
        <p>
            <span class="label">Brottsplats: </span><br />
            Skogslunden vid Jensens gård
        </p>
        <p>
            <span class="label">Brottsdatum: </span><br />
            2014-04-24
        </p>
        <p>
            <span class="label">Anmälare: </span><br />
            Maja Färjedal
        </p>
        <p>
            <span class="label">Telefon: </span><br />
            432-554 55 22
        </p>
        <p>
            <span class="label">Observationer:</span><br />
            Jag upptäckte soporna på en promenad den 24 april
        </p>
    </section>

    <section id="rightColumn">
        <h3>Utredning</h3>
        <p>
            <span class="label">Status:</span><br />
            Pågående
        </p>
        <p>
            <span class="label">Ansvarig avdelning: </span><br />
            Tekniska avloppshanteringen
        </p>
        <p>
            <span class="label">Handläggare: </span><br />
            Ada Bengtsson
        </p>
        <p>
            <span class="label">Provtagning: </span><br />
            Provtagning.pdf
        </p>
        <p>
            <span class="label">Ytterligare information: </span><br />
            Bland soporna hittades ett brev adresserat till Gösta Olsson
        </p>
        <p>
            <span class="label">Händelser: </span><br />
            Brev skickat till Gösta Olsson om soporna och anmälan som är gjord till polisen 2014-05-20
        </p>
        <p>
            <span class="label">Bilder: </span><br />
            <img src="../images/imagetest.jpg" alt="klicka på bilden" />
        </p>
    </section>

    <section id="bottomColumn">
        <h3>Redigera ärende</h3>
        <p>
            Ange enhet:
            <select name="department">
                <option selected="selected">Välj</option>
                <option value="unit0">Småstads Kommun</option>
                <option value="unit1">Tekniska Avloppshantering</option>
                <option value="unit2">Klimat och Energi</option>
                <option value="unit3">Miljö och Hälsoskydd</option>
                <option value="unit4">Natur och Skogsvård</option>
                <option value="unit5">Renhållning och Avfall</option>
            </select>
        </p>
        <p><input class="button" type="submit" value="Spara" /></p>
    </section>

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Coordinator/ReportCrime.cshtml
@{
}
<nav>
    <ul>
        <li><a asp-controller="Coordinator" asp-action="coordinator" class="reports">Start(Ärenden)</a></li>
        <li><a asp-controller="Coordinator" asp-action="reportCrime" class="reportAdd">Rapportera brott</a></li>
        <li class="right"><a asp-controller="Home" asp-action="Index" class="logout">Logga ut</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <h2>Rapportera brott</h2>
    <p class="info">Du är inloggad som samordnare</p>

    <p>Fyll i formuläret nedan, alla rutor markerade med stjärna (*) måste fyllas i</p>
    <form method="post" action="validate.html">
        <p>
            <input type="hidden" name="isSubmitted" value="true" />
        </p>
        <p>
            <span class="label">Var har brottet skett någonstans?</span><br />
            <input type="text" name="place" /> *
        </p>
        <p>
            <span class="label">Vilken typ av brott?</span><br />
            <input type="text" name="crime" /> *
        </p>
        <p>
            <span class="label">När skedde brottet?</span><br />
            <input type="text" name="crimeDate" /> *
        </p>
        <p>
            <span class="label">Ditt namn (för- och efternamn):</span><br />
            <input type="text" name="informersName" /> *
        </p>
        <p>
            <span class="label">Din telefon:</span><br />
            <input type="text" name="phone" /> *
        </p>
        <p>
            <span class="label">Beskriv din observation<br /> (ex. namn på misstänkt person):</span><br />
            <textarea name="observation" rows="5" cols="16"></textarea>
        </p>
        <p>
            <input class="button" value="Skicka in" onclick="location.href='@Url.Action("validate", "Coordinator")'" />
        </p>
    </form>

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/FAQ/FAQ.cshtml
@{
}
<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Service" asp-action="service"> Tjänster</a></li>
        <li><a asp-controller="FAQ" asp-action="faq">FAQ</a></li>
        <li><a asp-controller="Contact" asp-action="contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="LogIn" asp-action="logIn">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->


<div id="content">
    <section id="mainColumn">
        <h2>Frågor och svar om Miljöbrott</h2>
        <p class="info">Inga frågor är för dumma utom de som verkligen är det</p>

        <p>
            <span class="label">Varför måste jag fylla i mitt namn och telefonnummer?</span><br />
            Eftersom vi vill kunna kontakta dig för kompletterande information så måste vi veta vem du är.
        </p>

        <p>
            <span class="label">Vilka typer av miljöbrott kan man anmäla?</span><br />
            Allt möjligt, anmäl även om du är osäker. Vi utreder allt och tar beslut om det är något som ska vidare.
        </p>

        <p>
            <span class="label">Jag har tagit bilder och vill skicka med, hur gör jag?</span><br />
            Skicka in dem med vanlig post eller via email och berätta till vilken anmälan de hör ihop med
            (ange numret du fick när du gjorde anmälan).
        </p>

        <p>
            <span class="label">Vad gör jag med de dumma frågor jag har?</span><br />
            Du håller dem för dig själv, vi har inte tid att hantera sådana
        </p>

        <p>Fick du inte svar på din fråga? <a asp-controller="Contact" asp-action="contact">Maila eller ring till oss</a>.</p>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Home/Index.cshtml
@{
}

<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Service" asp-action="service"> Tjänster</a></li>
        <li><a asp-controller="FAQ" asp-action="faq">FAQ</a></li>
        <li><a asp-controller="Contact" asp-action="contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="LogIn" asp-action="logIn">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->


<div id="content">
    <section id="mainColumn">
        <h2>Välkommen att fylla i din anmälan av miljöbrott</h2>
        <p class="info">I Småstad är inga brott för små för att anmälas</p>

        <p>Fyll i formuläret nedan, alla rutor markerade med stjärna (*) måste fyllas i.</p>

        <form method="post" action="citizen/validate.html">
            <p>
                <input type="hidden" name="isSubmitted" value="true" />
            </p>
            <p>
                <span class="label">Var har brottet skett någonstans?</span><br />
                <input type="text" name="place" /> *
            </p>
            <p>
                <span class="label">Vilken typ av brott?</span><br />
                <input type="text" name="crime" /> *
            </p>
            <p>
                <span class="label">När skedde brottet?</span><br />
                <input type="text" name="crimeDate" /> *
            </p>
            <p>
                <span class="label">Ditt namn (för- och efternamn):</span><br />
                <input type="text" name="informersName" /> *
            </p>
            <p>
                <span class="label">Din telefon:</span><br />
                <input type="text" name="phone" /> *
            </p>
            <p>
                <span class="label">Beskriv din observation<br /> (ex. namn på misstänkt person):</span><br />
                <textarea name="observation" rows="5" cols="16"></textarea>
            </p>
            <p>
                <input class="button" value="Skicka in" onclick="location.href='@Url.Action("validate", "Citizen")'" />
            </p>
        </form>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/LogIn/LogIn.cshtml
@{
}
<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Service" asp-action="service"> Tjänster</a></li>
        <li><a asp-controller="FAQ" asp-action="faq">FAQ</a></li>
        <li><a asp-controller="Contact" asp-action="contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="LogIn" asp-action="logIn">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <section id="mainColumn">
        <h2>Inloggning för Småstads personal</h2>
        <p class="info">En säker tjänst från Småstads IT-avdelning</p>

        <form method="post" action="coordinator/startCoordinator.html">
            <p>
                <input type="hidden" name="isSubmitted" value="true" />
            </p>
            <p>
                <span class="label">Användarnamn:</span><br />
                <input type="text" name="user" />
            </p>
            <p>
                <span class="label">Lösenord:</span><br />
                <input type="password" name="password" />
            </p>
            <p>
                <!--Dessa länkar ska sedan tas bort då det är meningen att vid kontrollen av inloggningsuppgifter så hämtas rätt sida-->
                <a class="button" asp-controller="Coordinator" asp-action="coordinator">Inloggning av samordnare</a><br />
                <a class="button" asp-controller="Manager" asp-action="manager">Inloggning av chefer</a><br />
                <a class="button" asp-controller="Investigator" asp-action="investigator">Inloggning av handläggare</a>
            </p>
        </form>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->

Smastad/Smastad/Views/Service/Service.cshtml
@{
}

<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
        <li><a asp-controller="Service" asp-action="service"> Tjänster</a></li>
        <li><a asp-controller="FAQ" asp-action="faq">FAQ</a></li>
        <li><a asp-controller="Contact" asp-action="contact">Kontakt</a></li>
        <li class="right"><a class="login" asp-controller="LogIn" asp-action="logIn">Logga in (endast personal)</a></li>
    </ul>
</nav><!-- End Nav -->

<div id="content">
    <section id="mainColumn">
        <h2>Avdelningar och Tjänster</h2>
        <p class="info">Vi bryr oss om dig</p>

        <p>Folkhälsa - Hälso- och Sjukvård, Tandvård - Socialtjänst och omsorg - Trygghet och säkerhet</p>
        <p>Bygga och bo - Gator och parker - Kollektivtrafiken - Miljö- och hälsoskydd - Sophantering och återvinning</p>
        <p>Barn och utbildning - Kultur och fritid</p>
        <p>Företagsservice</p>
    </section><!-- End Left -->

    <aside id="sideColumn">
        <img src="~/images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
        <img src="~/images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
        <img src="~/images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
        <img src="~/images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
        <img src="~/images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
        <img src="~/images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
        <img src="~/images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
        <img src="~/images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
    </aside><!-- End Right -->

    <footer>
        &copy; Småstads Kommun All rights reserved.
    </footer>
</div><!-- End Content -->